name: Dataset Updater

on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      - name: Running Scripts
        run: |
          pip install requests openpyxl
          cd scripts
          python step1_global.py
          python step1_mx.py
          python replacer.py
          cd ..
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated datasets."
          git push
